---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpd-pod
spec:
  selector:
    matchLabels:
      app: httpd-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd-pod
    spec:
      containers:
      - name: httpd-pod
        image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME
