apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  selector:
      app: httpd-pod
  ports:
    - name: httpd
      port: 80
      protocol: TCP		
      targetPort: 80
      nodePort: 32120
  type: NodePort
